esphome:
  name: jumbobutton
  platform: ESP8266
  board: d1_mini

  on_boot:
    then:
      - output.turn_off: gpio_d6

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASSWORD

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jumbobutton Fallback Hotspot"
    password: !secret ESP_AP_PWD

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ESP_API_PWD

ota:
  password: !secret ESP_OTA_PWD

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: True
      mode: INPUT_PULLUP
    name: "Jumbo Button"
    on_multi_click:
    - timing:
      - ON for at most 500ms
      - OFF for at least 0.1s
      then:
        - homeassistant.event:
            event: esphome.jumbo_button_pressed
            data:
              title: Jumbo button was short-pressed
    - timing:
      - ON for 500ms to 2s
      - OFF for at least 0.1s
      then:
        - homeassistant.event:
            event: esphome.jumbo_button_long_pressed
            data:
              title: Jumbo button was long-pressed

# Because we don't have a spare ground pin, use an output set to off
# as ground.
output:
  - platform: gpio
    pin: D6
    id: gpio_d6

wled:

e131:
  method: unicast

light:
  - platform: fastled_spi
    chipset: APA102
    data_pin: D3
    clock_pin: D4
    num_leds: 3
    rgb_order: BGR
    name: "Jumbobutton Lights"
    effects:
      - addressable_rainbow:
      - wled:
      - e131:
          universe: 1
          channels: RGB
